# Generated by Django 4.1.1 on 2022-09-25 18:24

from django.db import migrations, models
import django.utils.timezone
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('content', django_quill.fields.QuillField(null=True, verbose_name='Содержание')),
                ('status', models.CharField(default='Опубликовано', max_length=10, verbose_name='Статус')),
                ('published', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата публикации')),
                ('video', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на видео')),
                ('image', models.ImageField(blank=True, upload_to='articles')),
                ('meta_keywords', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta keywords')),
                ('meta_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta description')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
